### ISSUE TITLE
CRS issues

### ISSUE THREAD

**Issue by rsbivand** [riatelab/cartography#54]
The getGridLayer example now fails with PROJ 6.1.0 on st_crs(x) == st_crs(y) with current **sf** (@edzer) and:

```
> mygrid <- getGridLayer(x = mtq, cellsize = 3e7, type = "hexagonal", var = "POP")
Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared) : 
  st_crs(x) == st_crs(y) is not TRUE
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.7.2"        "3.0.0"        "6.1.0"         "true" 
> debug(getGridLayer)
...
Browse[2]> st_crs(x)
Coordinate Reference System:
  EPSG: 32620 
  proj4string: "+proj=utm +zone=20 +datum=WGS84 +units=m +no_defs"
...
Browse[2]> st_crs(grid)
Coordinate Reference System:
  EPSG: 32620 
  proj4string: "+proj=utm +zone=20 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
Browse[2]> 
Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared) : 
  st_crs(x) == st_crs(y) is not TRUE
>
```

**Comment by rCarto** [comment]
Thank you for letting me know. My guess is that the problem is related to a mixed use of `sp` and `sf`.  Commit 3740956 make use of `sf` only and should fix the crs mismatch...

**Comment by rsbivand** [comment]
I've submitted **rgdal** anyway. I think @edzer knows how to set up CI with current PROJ and GDAL.

**Comment by edzer** [comment]
I do, but I don't use it. I'm using CI with ubuntugis-unstable PPA, which hasn't migrated to GDAL 3 yet.

**Comment by rsbivand** [comment]
The problem is still present. it is NOT **sp**/**sf**. It is probably PROJ version related.

**Comment by rCarto** [comment]
I've just retested the current master with @Nowosad docker (GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1) and it seems to work fine.
